### ISSUE TITLE
STATE OF THE PROJECT

### ISSUE THREAD

**Issue by bowvernon110391** [bcsoetta/apishinta#17]
Oke, sejauh ini kita sudah punya **REST API** yg ngikutin pedoman dari 

> Phil Sturgeon - Buidling APIS you won't hate

, dan sejauh ini sudah sesuai dengan prinsip **REST**. Coba kita list yang udah dibuat/belum dibuat di sini. Ini baru list kegiatan sementara, bisa nambah bisa kurang.

- [x] List resource apa saja yang digunakan di aplikasi 

> `CD`, `Penumpang`, `Kurs`, `detailCD`, ...etc

- [x] Controller class utk masing2 resource beserta `route` dan `method` nya. Cek file `api.php` untuk penambahan end point. Cek controller KursController.php untuk melihat contoh yang agak lengkap (untuk `DELETE` data belum dibuat karena ke depan kita akan tambahkan kapabilitas bawaan laravel "Soft Delete" untuk data-data yang bisa di hapus (lihat #13)
- [x] Test suite menggunakan `Behat`. Untuk cara install behat (bisa lihat issue #15)
- [x] API sudah dibuatkan "guards" berupa middleware untuk mencegah akses secara tidak benar (Lihat middleware `cors` di kelas `CORS.php`)
- [x] API sudah dibuatkan "guards" berupa middleware untuk mencegah akses yang tidak diijinkan. 
- [x] mekanisme integrasi "dummy" utk SSO. Lihat file `app\Helpers\Helper.php` lihat fungsi `getUserInfo`. Sejauh ini fungsi baru berjalan di environment `local`, utk `production` belum dibuat. (Tapi simpel kok cuman install library `jasny/sso`) terus implementasi 2/3 baris kode (we udh pernah integrasi utk `akang`, sangat simpel).
Dan lihat juga di fungsi tsb ada 2 data user dummy dengan role yg berbeda-beda. kalau mau tambah silahkan di tambahkan. 
- [x] mekanisme penomoran sudah ad, cukup panggil `getSequence(groupCode, year)`. Cuman kapan penomoran dilakukan? bagusnya ketika dokumen dirasa sudah cukup "valid"
- [x] mekanisme status utk dokumen (jadi ada kalanya dokumen tdk dapat dihapus kcuali statusnya masih open, kecuali oleh admin)
- [x] mekanisme logging aktifitas api (yg perlu aja)
- [x] dokumentasi sementara lihat #16

Issue ini akan terus diupdate sesuai perkembangan lebih lanjut. Jangan ditutup ya

**Comment by bcsoetta** [comment]
**Hot on the list**
> #16

**Comment by bcsoetta** [comment]
**Sudah bisa** 
- [ ] Input data CD
- [ ] Edit data CD
- [ ] Hapus data CD
- [ ] CRUD utk data penumpang
- [ ] Simulasi pembayaran CD, sebelum benar2 ditetapkan SPPBMCPnya.
